version: '3.3' 
services:
  payment.db: 
    image: mysql:8.0 
    command: --default-authentication-plugin=mysql_native_password 
    container_name: payment.db 
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: 123456 
    volumes:
      - /home/mysql-payment:/var/lib/mysql
    ports:
      - 33072:3306 
  payment.adminer:
    image: adminer 
    container_name: payment.adminer 
    depends_on:
      - payment.db 
    restart: always 
    ports: 
      - 17184:8080 
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123456
      PMA_HOST: payment.db
  payment.redis:
    image: redis:6.0
    container_name: payment.redis
  payment.php:
    build: ./env/nginx-php-fpm 
    image: wyveo/nginx-php-fpm:php74-modify 
    container_name: payment.system
    depends_on:
      - payment.db
    volumes:
      #- ./fourth_payment_system:/usr/share/nginx/html
      - ./fourth_merge_payment_colorful/full_system:/usr/share/nginx/html
    ports:
      - 18440:80

networks: 
  default: 
    external: 
      name: payment-bridge
